import mongoose, { Schema, Document, Model } from "mongoose";

export interface IMilestone {
  _id?: string; // Auto-generated by Mongo
  title: string;
  due_date: string;
  criteria: string;
  amount?: string; // 👈 NEW: Money tied to step

  status: "pending" | "in_review" | "approved" | "dispute";

  // 👈 NEW: Proof Data
  proof_url?: string;
  proof_notes?: string;
  completed_at?: Date;
}

export interface IProject extends Document {
  userId: string;
  contractName: string;
  summary: string;
  parties: string[];
  total_value: string;
  milestones: IMilestone[];
  vendorEmail?: string;
  vendorId?: string;
  vendorJoinedAt?: Date;
  status: "active" | "completed" | "archived";
  createdAt: Date;
}

const MilestoneSchema = new Schema<IMilestone>({
  title: { type: String, required: true },
  due_date: { type: String, default: "TBD" },
  criteria: { type: String, required: true },
  amount: { type: String }, // e.g. "$500"
  status: {
    type: String,
    enum: ["pending", "in_review", "approved", "dispute"],
    default: "pending",
  },
  proof_url: { type: String },
  proof_notes: { type: String },
  completed_at: { type: Date },
});

const ProjectSchema = new Schema<IProject>(
  {
    userId: { type: String, required: true, index: true },
    contractName: { type: String, required: true },
    summary: { type: String },
    parties: { type: [String] },
    total_value: { type: String },
    milestones: { type: [MilestoneSchema], default: [] },
    vendorEmail: { type: String },
    vendorId: { type: String },
    vendorJoinedAt: { type: Date },
    status: {
      type: String,
      enum: ["active", "completed", "archived"],
      default: "active",
    },
  },
  { timestamps: true }
);

export const Project: Model<IProject> =
  mongoose.models.Project || mongoose.model<IProject>("Project", ProjectSchema);
